2021-03-09 13:47:20,263 ERROR: Exception on /favicon.ico [GET] [in /home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/tom/moringa-core/Flask/blog/app/main/routes.py", line 16, in before_request
    g.locale = str(getocale())
NameError: name 'getocale' is not defined
2021-03-09 13:47:56,911 INFO: Microblog startup [in /home/tom/moringa-core/Flask/blog/app/__init__.py:68]
2021-03-09 13:47:58,824 ERROR: Exception on / [GET] [in /home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tom/moringa-core/Flask/blog/app/main/routes.py", line 40, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2021-03-09 13:48:06,781 ERROR: Exception on /index [GET] [in /home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tom/moringa-core/Flask/blog/app/main/routes.py", line 40, in index
    return render_template('index.html', title=_('Home'), form=form,
NameError: name '_' is not defined
2021-03-09 14:07:05,678 INFO: Microblog startup [in /home/tom/moringa-core/Flask/blog/app/__init__.py:68]
2021-03-09 14:07:08,287 ERROR: Exception on / [GET] [in /home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tom/moringa-core/Flask/blog/app/main/routes.py", line 40, in index
    return render_template('index.html', title=('Home'), form=form,
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/tom/moringa-core/Flask/blog/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %} {%block content%}
  File "/home/tom/moringa-core/Flask/blog/app/templates/base.html", line 127, in top-level template code
    {% endfor %} {% endif %} {% endwith %} {%block content%} {%endblock%}
  File "/home/tom/moringa-core/Flask/blog/app/templates/index.html", line 20, in block "content"
    {% endif %} {% for post in posts %} {% include "_posts.html" %} {% endfor %} {%
  File "/home/tom/moringa-core/Flask/blog/app/templates/_posts.html", line 7, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-03-09 14:07:46,106 INFO: Microblog startup [in /home/tom/moringa-core/Flask/blog/app/__init__.py:68]
2021-03-09 14:07:53,494 ERROR: Exception on / [POST] [in /home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/moringa-core/Flask/blog/env/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tom/moringa-core/Flask/blog/app/main/routes.py", line 24, in index
    language = guessanguage(form.post.data)
NameError: name 'guessanguage' is not defined
2021-03-09 14:50:59,178 INFO: Microblog startup [in /home/tom/moringa-core/Flask/blog/app/__init__.py:68]
